import { StyleSheet} from 'react-native'
import colours from './colour'


export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:colours.background
    },
    map:{
      flex:1
    }
})

// Enhanced modern styles for improved visual design
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  map: {
    flex: 1,
  },
  // Google Maps-style professional search container
  searchContainer: {
    position: 'absolute',
    top: 60,
    left: 16,
    right: 16,
    zIndex: 10,
    backgroundColor: '#ffffff',
    borderRadius: 28,
    paddingHorizontal: 20,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 0.5,
    borderColor: 'rgba(0, 0, 0, 0.04)',
  },
  searchContainerFocused: {
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 12,
    borderColor: '#4285F4',
    borderWidth: 1,
    transform: [{ scale: 1.02 }],
  },
  searchIcon: {
    marginRight: 16,
    opacity: 0.7,
  },
  searchInput: {
    flex: 1,
    fontSize: 17,
    color: '#202124',
    padding: 0,
    fontWeight: '400',
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  // Google Maps-style results container
  resultsContainer: {
    position: 'absolute',
    top: 130,
    left: 16,
    right: 16,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    maxHeight: 400,
    zIndex: 9,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 12,
    borderWidth: 0.5,
    borderColor: 'rgba(0, 0, 0, 0.04)',
  },
  resultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
    backgroundColor: '#ffffff',
  },
  resultIcon: {
    marginRight: 16,
    width: 24,
    textAlign: 'center',
    opacity: 0.8,
  },
  resultTextContainer: {
    flex: 1,
  },
  resultTitle: {
    fontSize: 16,
    color: '#202124',
    fontWeight: '500',
    marginBottom: 4,
    letterSpacing: 0.1,
  },
  resultSubtitle: {
    fontSize: 14,
    color: '#5f6368',
    fontWeight: '400',
    letterSpacing: 0.1,
  },
  noResults: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noResultsText: {
    marginTop: 12,
    fontSize: 16,
    color: '#95a5a6',
    fontWeight: '500',
  },
  // Enhanced markers with better colors and animations
  marker: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colours.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 6,
  },
  destinationMarker: {
    backgroundColor: '#27ae60',
    width: 42,
    height: 42,
    borderRadius: 21,
    transform: [{ scale: 1.1 }],
  },
  customDestinationMarker: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f39c12',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 6,
  },
  userLocationMarker: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colours.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 6,
  },
  userLocationPulse: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colours.primary,
    opacity: 0.3,
  },
  // Enhanced buttons with gradients and better design
  currentLocationButton: {
    position: 'absolute',
    bottom: 120,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.05)',
  },
  setDestinationButton: {
    position: 'absolute',
    bottom: 180,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colours.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colours.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  // Enhanced navigation panel with modern design
  navigationPanel: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'white',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 12,
    zIndex: 15,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.05)',
  },
  navigationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  navigationTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#2c3e50',
  },
  destinationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    backgroundColor: 'rgba(30, 144, 255, 0.1)',
    padding: 12,
    borderRadius: 12,
  },
  destinationName: {
    fontSize: 16,
    marginLeft: 12,
    color: '#2c3e50',
    fontWeight: '600',
  },
  routeInfo: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
    backgroundColor: '#f8f9fa',
    padding: 16,
    borderRadius: 12,
  },
  routeInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  routeInfoText: {
    marginLeft: 6,
    fontSize: 16,
    color: '#34495e',
    fontWeight: '600',
  },
  navigationControls: {
    alignItems: 'center',
  },
  stopButton: {
    backgroundColor: '#e74c3c',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
    shadowColor: '#e74c3c',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  stopButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  // Enhanced modal design
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    backdropFilter: 'blur(5px)',
  },
  modalContent: {
    backgroundColor: 'white',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 20,
    textAlign: 'center',
    color: '#2c3e50',
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#f8f9fa',
    marginBottom: 8,
  },
  modalOptionText: {
    fontSize: 16,
    marginLeft: 16,
    color: '#2c3e50',
    fontWeight: '500',
  },
  modalCancel: {
    padding: 16,
    alignItems: 'center',
    marginTop: 12,
  },
  modalCancelText: {
    fontSize: 16,
    color: '#e74c3c',
    fontWeight: '600',
  },
  // Map Controls Styles
  mapControlsContainer: {
    position: 'absolute',
    right: 20,
    top: '50%',
    transform: [{ translateY: -100 }],
    zIndex: 5,
  },
  zoomControls: {
    backgroundColor: 'white',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 6,
    marginBottom: 12,
  },
  zoomControlsDark: {
    backgroundColor: '#2d2d2d',
  },
  zoomButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
  },
  zoomButtonDark: {
    borderBottomColor: '#5f6368',
  },
  compassButton: {
    width: 44,
    height: 44,
    backgroundColor: 'white',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 6,
    marginBottom: 12,
  },
  compassButtonDark: {
    backgroundColor: '#2d2d2d',
  },
  mapStyleButton: {
    minWidth: 44,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'white',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 6,
    gap: 6,
  },
  mapStyleButtonDark: {
    backgroundColor: '#2d2d2d',
  },
  mapStyleText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#2c3e50',
  },
  mapStyleTextDark: {
    color: '#e8eaed',
  },
  // Callout Styles
  callout: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.05)',
  },
  calloutContent: {
    minWidth: 200,
    padding: 16,
  },
  calloutTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2c3e50',
    marginBottom: 4,
  },
  calloutSubtitle: {
    fontSize: 14,
    color: '#7f8c8d',
    marginBottom: 12,
  },
  calloutActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calloutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    flex: 1,
    marginHorizontal: 4,
    justifyContent: 'center',
  },
  calloutButtonText: {
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 6,
  },
  // Voice Guidance Styles
  navigationControlRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  voiceToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: '#f8f9fa',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  voiceToggleButtonActive: {
    backgroundColor: 'rgba(39, 174, 96, 0.1)',
    borderColor: '#27ae60',
  },
  voiceToggleText: {
    fontSize: 14,
    color: '#95a5a6',
    fontWeight: '600',
    marginLeft: 6,
  },
  voiceToggleTextActive: {
    color: '#27ae60',
  },
  // Enhanced Search Bar Elements
  voiceSearchButton: {
    minWidth: 40,
    minHeight: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    marginLeft: 8,
  },
  voiceSearchButtonActive: {
    backgroundColor: 'rgba(234, 67, 53, 0.1)',
  },
  clearSearchButton: {
    minWidth: 40,
    minHeight: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    borderRadius: 20,
  },
  searchDivider: {
    width: 1,
    height: 24,
    backgroundColor: '#dadce0',
    marginHorizontal: 12,
  },
  searchDividerDark: {
    backgroundColor: '#5f6368',
  },
  favoritesButton: {
    minWidth: 40,
    minHeight: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  
  // Dark Mode Search Styles
  searchContainerDark: {
    backgroundColor: '#2d2d2d',
    borderColor: '#5f6368',
  },
  searchInputDark: {
    color: '#e8eaed',
  },

  // Auto-suggestions
  autoSuggestionsContainer: {
    position: 'absolute',
    top: 115,
    left: 16,
    right: 16,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    maxHeight: 200,
    zIndex: 11,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 0.5,
    borderColor: 'rgba(0, 0, 0, 0.04)',
  },
  autoSuggestionsContainerDark: {
    backgroundColor: '#2d2d2d',
    borderColor: '#5f6368',
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
  },
  suggestionItemDark: {
    borderBottomColor: '#5f6368',
  },
  suggestionIcon: {
    marginRight: 12,
  },
  suggestionText: {
    fontSize: 16,
    color: '#202124',
    fontWeight: '400',
  },
  suggestionTextDark: {
    color: '#e8eaed',
  },

  // Quick Shortcuts
  quickShortcutsContainer: {
    position: 'absolute',
    top: 130,
    left: 16,
    right: 16,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    maxHeight: 300,
    zIndex: 9,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 0.5,
    borderColor: 'rgba(0, 0, 0, 0.04)',
    paddingVertical: 16,
  },
  quickShortcutsContainerDark: {
    backgroundColor: '#2d2d2d',
    borderColor: '#5f6368',
  },
  quickShortcutsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#5f6368',
    marginHorizontal: 20,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  quickShortcutsTitleDark: {
    color: '#9aa0a6',
  },
  shortcutItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
  },
  shortcutItemDark: {
    borderBottomColor: '#5f6368',
  },
  shortcutIcon: {
    marginRight: 16,
  },
  shortcutText: {
    flex: 1,
    fontSize: 16,
    color: '#202124',
    fontWeight: '400',
  },
  shortcutTextDark: {
    color: '#e8eaed',
  },
  favoritesContainer: {
    position: 'absolute',
    top: 120,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 15,
    maxHeight: 350,
    zIndex: 9,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    backdropFilter: 'blur(10px)',
  },
  favoritesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
  },
  favoritesTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2c3e50',
  },
  favoriteItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
  },
  favoriteIcon: {
    marginRight: 16,
  },
  favoriteTextContainer: {
    flex: 1,
  },
  favoriteTitle: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '600',
    marginBottom: 2,
  },
  favoriteSubtitle: {
    fontSize: 14,
    color: '#7f8c8d',
    fontWeight: '400',
  },
  removeFavoriteButton: {
    padding: 8,
    marginRight: 12,
  },
  noFavorites: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noFavoritesText: {
    marginTop: 12,
    fontSize: 16,
    color: '#95a5a6',
    fontWeight: '500',
  },
  noFavoritesSubtext: {
    marginTop: 8,
    fontSize: 14,
    color: '#bdc3c7',
    textAlign: 'center',
    lineHeight: 20,
  },
  // Google Maps-style category filters
  categoryFilters: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
    backgroundColor: '#ffffff',
  },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 8,
    borderRadius: 20,
    backgroundColor: '#f8f9fa',
    borderWidth: 0.5,
    borderColor: '#dadce0',
  },
  categoryButtonActive: {
    backgroundColor: '#4285F4',
    borderColor: '#4285F4',
    shadowColor: '#4285F4',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  categoryButtonText: {
    fontSize: 13,
    color: '#5f6368',
    fontWeight: '500',
    marginLeft: 6,
    letterSpacing: 0.1,
  },
  categoryButtonTextActive: {
    color: '#ffffff',
    fontWeight: '600',
  },
  noResultsSubtext: {
    marginTop: 8,
    fontSize: 14,
    color: '#95a5a6',
    textAlign: 'center',
  },
  recentSearchesContainer: {
    position: 'absolute',
    top: 120,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 15,
    zIndex: 9,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    backdropFilter: 'blur(10px)',
  },
  recentSearchesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
  },
  recentSearchesTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2c3e50',
  },
  clearRecentText: {
    fontSize: 14,
    color: '#e74c3c',
    fontWeight: '500',
  },
  recentSearchItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
  },
  recentSearchIcon: {
    marginRight: 16,
  },
  recentSearchTextContainer: {
    flex: 1,
  },
  recentSearchTitle: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
    marginBottom: 2,
  },
  recentSearchSubtitle: {
    fontSize: 14,
    color: '#7f8c8d',
  },
  // Weather Icon Button - Small and clean
  weatherIconButton: {
    position: 'absolute',
    top: 130,
    right: 20,
    width: 44,
    height: 44,
    backgroundColor: '#ffffff',
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 0.5,
    borderColor: 'rgba(0, 0, 0, 0.04)',
    zIndex: 8,
  },
  // Weather Modal Styles
  weatherModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  weatherModal: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 320,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 20,
  },
  weatherModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  weatherModalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#202124',
  },
  weatherModalContent: {
    alignItems: 'center',
  },
  weatherMainInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  weatherModalTemp: {
    fontSize: 36,
    fontWeight: '300',
    color: '#202124',
    marginLeft: 16,
  },
  weatherModalCondition: {
    fontSize: 18,
    color: '#5f6368',
    fontWeight: '400',
    marginBottom: 24,
    textTransform: 'capitalize',
  },
  weatherModalStats: {
    width: '100%',
  },
  weatherModalStat: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    marginBottom: 8,
  },
  weatherModalStatText: {
    fontSize: 16,
    color: '#202124',
    marginLeft: 12,
    fontWeight: '400',
  },

  // Top Right Controls
  topRightControls: {
    position: 'absolute',
    top: 60,
    right: 20,
    zIndex: 10,
  },
  themeToggleButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 0.5,
    borderColor: 'rgba(0, 0, 0, 0.04)',
  },
  themeToggleButtonDark: {
    backgroundColor: '#2d2d2d',
    borderColor: '#5f6368',
  },

  // Google Maps Style Bottom Bar
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#ffffff',
    borderTopWidth: 0.5,
    borderTopColor: 'rgba(0, 0, 0, 0.08)',
    paddingBottom: 34, // Safe area padding
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
  },
  bottomBarDark: {
    backgroundColor: '#2d2d2d',
    borderTopColor: '#5f6368',
  },
  bottomBarContent: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
  },
  bottomBarButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  bottomBarButtonText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#5f6368',
    marginTop: 4,
    textAlign: 'center',
  },
  bottomBarButtonTextDark: {
    color: '#9aa0a6',
  },
  savedButtonContainer: {
    position: 'relative',
  },
  savedBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#ea4335',
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  savedBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#ffffff',
  },

  // Bottom Sheet Styles
  bottomSheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  bottomSheetBackdrop: {
    flex: 1,
  },
  bottomSheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingHorizontal: 20,
    paddingBottom: 34,
    maxHeight: '70%',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 12,
  },
  bottomSheetDark: {
    backgroundColor: '#2d2d2d',
  },
  bottomSheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#dadce0',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  bottomSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  locationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  locationIcon: {
    marginRight: 16,
  },
  locationTextInfo: {
    flex: 1,
  },
  locationTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#202124',
    marginBottom: 4,
  },
  locationTitleDark: {
    color: '#e8eaed',
  },
  locationSubtitle: {
    fontSize: 14,
    color: '#5f6368',
    fontWeight: '400',
    textTransform: 'capitalize',
  },
  locationSubtitleDark: {
    color: '#9aa0a6',
  },
  favoriteToggle: {
    padding: 8,
  },
  bottomSheetActions: {
    flexDirection: 'row',
    marginBottom: 24,
    gap: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 12,
    gap: 8,
  },
  primaryActionButton: {
    backgroundColor: '#4285F4',
  },
  secondaryActionButton: {
    backgroundColor: '#f8f9fa',
    borderWidth: 1,
    borderColor: '#dadce0',
  },
  secondaryActionButtonDark: {
    backgroundColor: '#3c4043',
    borderColor: '#5f6368',
  },
  primaryActionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  secondaryActionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4285F4',
  },
  secondaryActionTextDark: {
    color: '#8ab4f8',
  },
  locationDetails: {
    gap: 12,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    gap: 12,
  },
  detailItemDark: {
    backgroundColor: '#3c4043',
  },
  detailText: {
    fontSize: 14,
    color: '#5f6368',
    fontWeight: '400',
  },
  detailTextDark: {
    color: '#9aa0a6',
  },

  // Dark Mode Modal Styles
  modalContentDark: {
    backgroundColor: '#2d2d2d',
  },
  modalTitleDark: {
    color: '#e8eaed',
  },
  modalOptionDark: {
    backgroundColor: '#3c4043',
  },
  modalOptionTextDark: {
    color: '#e8eaed',
  },
});